### ISSUE TITLE
错误：✘ app.json 格式不正确，请按照脚手架 https://github.com/youwenda/taojimu-miniapp-demo/blob/master/app.json 格式进行补充

### ISSUE THREAD

**Issue by HyhBlazing** [youwenda/taojimu-miniapp-demo#3]
到底是哪里不正确呢？

**Comment by youwenda** [comment]
主要检测了app.json 中是否引入了淘积木插件。这里的插件名称必须为 `taojimu` : 

```
"plugins": {
    "taojimu": {
      "version": "*",
      "provider": "3000000040708051"
    }
  }
```
开发过程中遇到的问题请钉钉扫码进入答疑群，可以得到尽快答复。
![image](https://user-images.githubusercontent.com/2204911/182990219-4f0e5562-c2fc-4e9e-a83e-4e3db8c4230e.png)
